# Generated by Django 3.0.3 on 2020-09-23 19:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('micros', '0002_auto_20200923_1454'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('sex', models.IntegerField(choices=[(5, 'Male'), (-161, 'Female')], default=5)),
                ('age', models.SmallIntegerField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('weightUnit', models.FloatField(choices=[(2.20462, 'Pounds'), (1, 'Kilograms')], default=1)),
                ('height', models.FloatField(blank=True, null=True)),
                ('heightUnit', models.FloatField(choices=[(2.54, 'Inches'), (1, 'Centimeters')], default=1)),
                ('activityLevel', models.FloatField(choices=[(1.2, 'Sedentary'), (1.375, 'Light Activity'), (1.55, 'Moderately Active'), (1.725, 'Very Active'), (1.9, 'Extremely Active')], default=1.2)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(blank=True, null=True)),
                ('weightUnit', models.FloatField(choices=[(2.20462, 'Pounds'), (1, 'Kilograms')], default=1)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='weights', to='users.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal', models.CharField(choices=[('b', 'Breakfast'), ('ms', 'Morning Snack'), ('l', 'Lunch'), ('as', 'Afternoon Snack'), ('d', 'Dinner'), ('es', 'Evening Snack'), ('mns', 'Midnight Snack')], default='b', max_length=3)),
                ('image', models.ImageField(blank=True, null=True, upload_to='meal_pics')),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='meal_photos', to='users.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('b', 'Breakfast'), ('ms', 'Morning Snack'), ('l', 'Lunch'), ('as', 'Afternoon Snack'), ('d', 'Dinner'), ('es', 'Evening Snack'), ('mns', 'Midnight Snack')], default='b', max_length=3)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='meals', to='users.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taken_serving', models.FloatField(blank=True, null=True)),
                ('returned_serving', models.FloatField(blank=True, null=True)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='foods_in_photo', to='micros.Mainfooddesc')),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='photos_foods', to='users.Photo')),
                ('servingSize', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portion_sizes', to='micros.Foodweights')),
            ],
        ),
    ]
