# Generated by Django 3.1.3 on 2020-11-25 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Addfooddesc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seqnum', models.SmallIntegerField(db_column='SeqNum')),
                ('additionalfooddescription', models.CharField(db_column='AddFoodDesc', max_length=80)),
                ('startdate', models.DateTimeField(db_column='StartDate')),
                ('enddate', models.DateTimeField(db_column='EndDate')),
            ],
            options={
                'db_table': 'fndds_AddFoodDesc',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fnddsingred',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seqnum', models.SmallIntegerField(db_column='SeqNum')),
                ('ingredientcode', models.IntegerField(db_column='IngredCode')),
                ('ingredientdescription', models.CharField(db_column='IngredDesc', max_length=240)),
                ('amount', models.FloatField(db_column='Amount')),
                ('measure', models.CharField(blank=True, db_column='Measure', max_length=3, null=True)),
                ('retentioncode', models.SmallIntegerField(db_column='RetentionCode')),
                ('ingredientweight', models.FloatField(db_column='IngredientWeight')),
                ('startdate', models.DateTimeField(db_column='StartDate')),
                ('enddate', models.DateTimeField(db_column='EndDate')),
            ],
            options={
                'db_table': 'fndds_Ingred',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fnddsnutval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nutrientvalue', models.FloatField(db_column='NutrientValue')),
                ('startdate', models.DateTimeField(db_column='StartDate')),
                ('enddate', models.DateTimeField(db_column='EndDate')),
            ],
            options={
                'db_table': 'FNDDSNutVal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Foodportiondesc',
            fields=[
                ('portioncode', models.IntegerField(db_column='PortionCode', primary_key=True, serialize=False)),
                ('portiondescription', models.CharField(db_column='PortionDesc', max_length=120)),
                ('startdate', models.DateTimeField(db_column='StartDate')),
                ('enddate', models.DateTimeField(db_column='EndDate')),
            ],
            options={
                'db_table': 'fndds_FoodPortionDesc',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Foodweights',
            fields=[
                ('subcode', models.IntegerField(blank=True, db_column='Subcode', null=True)),
                ('seqnum', models.SmallIntegerField(db_column='SeqNum')),
                ('portionweight', models.FloatField(db_column='PortionWeight')),
                ('startdate', models.DateTimeField(db_column='StartDate')),
                ('enddate', models.DateTimeField(db_column='EndDate')),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'fndds_FoodWeights',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mainfooddesc',
            fields=[
                ('foodcode', models.IntegerField(db_column='FoodCode', primary_key=True, serialize=False)),
                ('mainfooddescription', models.CharField(db_column='MainFoodDesc', max_length=200)),
                ('wweia_categorynumber', models.IntegerField(db_column='WWEIACategoryNumber')),
                ('wweia_categorydescription', models.CharField(db_column='WWEIACategoryDesc', max_length=80)),
                ('startdate', models.DateTimeField(db_column='StartDate')),
                ('enddate', models.DateTimeField(db_column='EndDate')),
            ],
            options={
                'db_table': 'fndds_MainFoodDesc',
                'ordering': ['foodcode'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nutdesc',
            fields=[
                ('nutrientcode', models.SmallIntegerField(db_column='Nutrientcode', primary_key=True, serialize=False)),
                ('nutrientdescription', models.CharField(db_column='NutrientDesc', max_length=45)),
                ('tagname', models.CharField(blank=True, db_column='Tagname', max_length=15, null=True)),
                ('unit', models.CharField(db_column='Unit', max_length=10)),
                ('decimals', models.SmallIntegerField(db_column='Decimals')),
            ],
            options={
                'db_table': 'fndds_NutDesc',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Subcodedesc',
            fields=[
                ('subcode', models.IntegerField(db_column='Subcode', primary_key=True, serialize=False)),
                ('subcode_description', models.CharField(db_column='SubcodeDescn', max_length=80)),
                ('start_date', models.DateTimeField(db_column='StartDate')),
                ('end_date', models.DateTimeField(db_column='EndDate')),
            ],
            options={
                'db_table': 'SubcodeDesc',
                'managed': False,
            },
        ),
    ]
