# Generated by Django 3.0.3 on 2020-09-17 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Addfooddesc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seqnum', models.SmallIntegerField(db_column='SeqNum')),
                ('additionalfooddescription', models.CharField(db_column='AdditionalFoodDescription', max_length=80)),
                ('startdate', models.DateTimeField(db_column='StartDate')),
                ('enddate', models.DateTimeField(db_column='EndDate')),
            ],
            options={
                'db_table': 'AddFoodDesc',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Foodportiondesc',
            fields=[
                ('portioncode', models.IntegerField(db_column='PortionCode', primary_key=True, serialize=False)),
                ('portiondescription', models.CharField(db_column='PortionDescription', max_length=120)),
                ('startdate', models.DateTimeField(db_column='StartDate')),
                ('enddate', models.DateTimeField(db_column='EndDate')),
            ],
            options={
                'db_table': 'FoodPortionDesc',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Foodweights',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodcode', models.IntegerField(db_column='FoodCode')),
                ('subcode', models.IntegerField(blank=True, db_column='Subcode', null=True)),
                ('seqnum', models.SmallIntegerField(db_column='SeqNum')),
                ('portionweight', models.FloatField(db_column='PortionWeight')),
                ('startdate', models.DateTimeField(db_column='StartDate')),
                ('enddate', models.DateTimeField(db_column='EndDate')),
            ],
            options={
                'db_table': 'FoodWeights',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mainfooddesc',
            fields=[
                ('foodcode', models.IntegerField(db_column='FoodCode', primary_key=True, serialize=False)),
                ('mainfooddescription', models.CharField(db_column='MainFoodDescription', max_length=200)),
                ('wweia_categorynumber', models.IntegerField(db_column='WWEIA_CategoryNumber')),
                ('wweia_categorydescription', models.CharField(db_column='WWEIA_CategoryDescription', max_length=80)),
                ('startdate', models.DateTimeField(db_column='StartDate')),
                ('enddate', models.DateTimeField(db_column='EndDate')),
            ],
            options={
                'db_table': 'MainFoodDesc',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fnddsingred',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seqnum', models.SmallIntegerField(db_column='SeqNum')),
                ('ingredientcode', models.IntegerField(db_column='IngredientCode')),
                ('ingredientdescription', models.CharField(db_column='IngredientDescription', max_length=150)),
                ('amount', models.DecimalField(db_column='Amount', decimal_places=3, max_digits=7)),
                ('measure', models.CharField(blank=True, db_column='Measure', max_length=2, null=True)),
                ('portioncode', models.IntegerField(blank=True, db_column='PortionCode', null=True)),
                ('retentioncode', models.IntegerField(db_column='RetentionCode')),
                ('ingredientweight', models.DecimalField(db_column='IngredientWeight', decimal_places=3, max_digits=7)),
                ('startdate', models.DateTimeField(db_column='StartDate')),
                ('enddate', models.DateTimeField(db_column='EndDate')),
                ('foodcode', models.ForeignKey(db_column='FoodCode', on_delete=django.db.models.deletion.DO_NOTHING, related_name='ingredients', to='micros.Mainfooddesc')),
            ],
            options={
                'db_table': 'FnddsIngred',
                'managed': True,
            },
        ),
    ]
