# Generated by Django 3.1.3 on 2020-11-26 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('micros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='T1Dexiimages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.BigIntegerField(blank=True, null=True)),
                ('imageid', models.TextField(blank=True, db_column='ImageId', null=True)),
                ('subjectid', models.TextField(blank=True, db_column='SubjectId', null=True)),
                ('time', models.TextField(blank=True, db_column='Time', null=True)),
                ('mealid', models.TextField(blank=True, db_column='MealId', null=True)),
            ],
            options={
                'db_table': 'T1DexiImages',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='T1Deximeal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.BigIntegerField(blank=True, null=True)),
                ('subjectid', models.TextField(blank=True, db_column='SubjectId', null=True)),
                ('date', models.TextField(blank=True, db_column='Date', null=True)),
                ('mealtypedesc', models.TextField(blank=True, db_column='MealTypeDesc', null=True)),
                ('mealdescription', models.TextField(blank=True, db_column='MealDescription', null=True)),
                ('mealid', models.TextField(blank=True, db_column='MealId', null=True)),
            ],
            options={
                'db_table': 'T1Deximeal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='T1Dexiimages_NEW',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.BigIntegerField(blank=True, null=True)),
                ('imageid', models.TextField(blank=True, db_column='ImageId', null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='study_pics/T1Dexi')),
                ('subjectid', models.TextField(blank=True, db_column='SubjectId', null=True)),
                ('time', models.TextField(blank=True, db_column='Time', null=True)),
                ('mealid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='micros.t1deximeal')),
            ],
            options={
                'db_table': 'T1DexiImages_NEW',
                'managed': True,
            },
        ),
    ]
