# Generated by Django 3.0.3 on 2020-09-23 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fnddsnutval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nutrientvalue', models.FloatField(db_column='NutrientValue')),
                ('startdate', models.DateTimeField(db_column='StartDate')),
                ('enddate', models.DateTimeField(db_column='EndDate')),
            ],
            options={
                'db_table': 'FNDDSNutVal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nutdesc',
            fields=[
                ('nutrientcode', models.SmallIntegerField(db_column='Nutrientcode', primary_key=True, serialize=False)),
                ('nutrientdescription', models.CharField(db_column='NutrientDescription', max_length=45)),
                ('tagname', models.CharField(blank=True, db_column='Tagname', max_length=15, null=True)),
                ('unit', models.CharField(db_column='Unit', max_length=10)),
                ('decimals', models.SmallIntegerField(db_column='Decimals')),
            ],
            options={
                'db_table': 'NutDesc',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Subcodedesc',
            fields=[
                ('subcode', models.IntegerField(db_column='Subcode', primary_key=True, serialize=False)),
                ('subcode_description', models.CharField(db_column='Subcode description', max_length=80)),
                ('start_date', models.DateTimeField(db_column='Start date')),
                ('end_date', models.DateTimeField(db_column='End date')),
            ],
            options={
                'db_table': 'SubcodeDesc',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='fnddsingred',
            options={'managed': False},
        ),
    ]
