# Generated by Django 3.0.3 on 2020-09-23 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('micros', '0002_auto_20200923_1454'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='fnddsingred',
            table='FNDDSIngred',
        ),
    ]
